# Generated by Django 3.2.3 on 2021-05-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=75, unique=True),
        ),
    ]
