version: '3'

services: 
    selenium:
        build: .
        command: python naukri_scraper.py
        ports:
            - 4000:4000
        volumes:
            - ./data/:/data/
        privileged: true